steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/photonics-research-dashboard:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/photonics-research-dashboard:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'photonics-research-dashboard',
      '--image', 'gcr.io/$PROJECT_ID/photonics-research-dashboard:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'ANTHROPIC_API_KEY=$$ANTHROPIC_API_KEY,TAVILY_API_KEY=$$TAVILY_API_KEY,OPENROUTER_API_KEY=$$OPENROUTER_API_KEY'
    ]

images:
  - 'gcr.io/$PROJECT_ID/photonics-research-dashboard:$COMMIT_SHA'

timeout: '1500s'

options:
  logging: CLOUD_LOGGING_ONLY
