#!/bin/bash
set -e

# Define variables
PROJECT_ID="axiomatic-ai-001"  # Use the same project ID as the example
REPO_NAME="20250314.Langgraph_MCP"
BRANCH_NAME="master"
TRIGGER_NAME="photonics-research-dashboard-build-deploy"
REGION="us-central1"

# Display instructions
echo "=== Google Cloud Build Trigger Setup ==="
echo "This script provides instructions for setting up a Cloud Build trigger for the Photonics Research Dashboard."
echo ""
echo "Prerequisites:"
echo "1. You must have a Google Cloud account with access to the ${PROJECT_ID} project"
echo "2. The Cloud Build and Cloud Run APIs must be enabled in your project"
echo ""
echo "Step 1: Connect your GitHub repository to Cloud Build"
echo "1. Go to Cloud Build > Triggers: https://console.cloud.google.com/cloud-build/triggers?project=${PROJECT_ID}"
echo "2. Click 'Connect Repository'"
echo "3. Select 'GitHub (Cloud Build GitHub App)'"
echo "4. Follow the prompts to authenticate with GitHub and select your repository: ${REPO_NAME}"
echo ""
echo "Step 2: Create a Cloud Build trigger"
echo "1. After connecting your repository, click 'Create Trigger'"
echo "2. Set the following:"
echo "   - Name: ${TRIGGER_NAME}"
echo "   - Region: ${REGION}"
echo "   - Event: Push to a branch"
echo "   - Repository: ${REPO_NAME}"
echo "   - Branch: ^${BRANCH_NAME}$"
echo "   - Configuration: Cloud Build configuration file (yaml or json)"
echo "   - Cloud Build configuration file location: cloudbuild.yaml"
echo ""
echo "Step 3: Set up environment variables in Cloud Build"
echo "1. Go to Cloud Build > Settings: https://console.cloud.google.com/cloud-build/settings?project=${PROJECT_ID}"
echo "2. Click on 'Create Secret'"
echo "3. Create the following secrets:"
echo "   - ANTHROPIC_API_KEY: Your Anthropic API key"
echo "   - TAVILY_API_KEY: Your Tavily API key"
echo "   - OPENROUTER_API_KEY: Your OpenRouter API key (optional)"
echo ""
echo "Step 4: Run the trigger manually or push to your branch"
echo "1. Go to Cloud Build > Triggers"
echo "2. Find your trigger and click 'Run Trigger'"
echo "3. Select the branch (${BRANCH_NAME}) and click 'Run'"
echo ""
echo "After deployment, access your dashboard at:"
echo "https://photonics-research-dashboard-[hash].a.run.app"
echo ""
echo "To get the exact URL, run:"
echo "gcloud run services describe photonics-research-dashboard --platform managed --region ${REGION} --format \"value(status.url)\""
echo ""
echo "Note: All operations are performed within Docker containers to ensure proper isolation and security."
